version: '3.3'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    # environment:
    #  - POSTGRES_DB=my_db
    #  - POSTGRES_USER=root
    #  - POSTGRES_PASSWORD=123456
    env_file:
      - db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    # environment:
    #  - PGADMIN_DEFAULT_EMAIL=root@admin.com
    #  - PGADMIN_DEFAULT_PASSWORD=root
    env_file:
      - db.env
    depends_on:
      - postgres
  # mysql:
  #   image: mysql:5
  #   env_file:
  #     - db.env
  #   ports:
  #   - '3306:3306'
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   env_file:
  #     - db.env
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     - mysql
